culinary/blog/urls.py
from django.urls import path
from . import views
from django.views.decorators.cache import cache_page

app_name = 'blog'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('comment/<int:pk>/', views.CreateComment.as_view(), name='create_comment'),
    path('<slug:slug>/<slug:post_slug>', views.PostDetailView.as_view(), name='post_single'),
    path('<slug:slug>/', views.PostListView.as_view(), name='post_list'),
]

culinary/contact/urls.py
from django.urls import path
from .views import ContactView, AboutView, CreateContact

app_name = 'contact'

urlpatterns = [
    path('contact/', ContactView.as_view(), name='contact'),
    path('about/', AboutView.as_view(), name='about'),
    path('feedback/', CreateContact.as_view(), name='feedback')
]

culinary/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('people/', include('contact.urls', namespace='contact'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

culinary/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify
from mptt.models import MPTTModel, TreeForeignKey

class Category(MPTTModel):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)
    parent = TreeForeignKey('self', related_name='children', on_delete=models.SET_NULL, null=True, blank=True)
    
    def __str__(self) -> str:
        return self.name

    class MPTTMeta:
        order_insertion_by = ['name']

class Tag(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)

    def __str__(self) -> str:
        return self.name

class Post(models.Model):
    author = models.ForeignKey(User, related_name='posts', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='articles/')
    text = models.TextField()
    category = models.ForeignKey(Category, related_name='post', on_delete=models.SET_NULL, null=True)
    tags = models.ManyToManyField(Tag, related_name='post')
    created_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=200, unique=True)

    def __str__(self) -> str:
        return self.title        
    
    def get_absolute_url(self):
        return reverse('blog:post_single', kwargs={'slug':self.category.slug, 'post_slug': self.slug})
    
    def get_recipes(self):
        return self.recipes.all()
    
    def get_comment(self):
        return self.comment.all()


class Recipe(models.Model):
    name = models.CharField(max_length=100)
    serves = models.CharField(max_length=50)
    prep_time = models.PositiveIntegerField(default=0)
    cook_time = models.PositiveIntegerField(default=0)
    ingredients = models.TextField()
    direction = models.TextField
    post = models.ForeignKey(Post, related_name='recipes', on_delete=models.SET_NULL, blank=True, null=True)


class Coment(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)
    website = models.CharField(max_length=100)
    message = models.TextField(max_length=500)
    create_at = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post, related_name='comment', on_delete=models.CASCADE)

culinary/contact/models.py
from django.db import models

class ContactModel(models.Model):
    """ Класс модели обратной связи """
    name = models.CharField(max_length=50)
    email = models.EmailField()
    website = models.URLField(blank=True, null=True)
    message = models.TextField(max_length=5000)
    create_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f'{self.name} - {self.email}'


class ContactLink(models.Model):
    """  Класс модели контактов """
    icon = models.FileField(upload_to='icons/')
    name = models.CharField(max_length=200)

    def __str__(self) -> str:
        return self.name


class About(models.Model):
    """ Класс модели страницы О нас """
    name = models.CharField(max_length=200, default='')
    text = models.TextField()
    mini_text = models.TextField()

    def get_first_image(self):
        item = self.about_images.first()
        return item.image.url

    def get_images(self):
        return self.about_images.order_by('id')[1:]


class ImageAbout(models.Model):
    """ Класс модели изображений страницы О нас """
    image = models.FileField(upload_to='about/')
    page = models.ForeignKey(About, related_name='about_images', on_delete=models.CASCADE)
    alt = models.CharField(max_length=100)


class Social(models.Model):
    """ Класс модели социальных сетей страницы О нас """
    icon = models.FileField(upload_to='icons/')
    name = models.CharField(max_length=200)
    link = models.URLField()

culinary/gallery/models.py
from enum import auto
from django.db import models

class Photo(models.Model):
    """ класс модели фото галереи изображений  """
    name = models.CharField(max_length=250)
    image = models.ImageField(upload_to='gallery/')
    captions = models.TextField(max_length=255, blank=True)
    create_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=255)

    class Meta:
        ordering = ['name']
    
    def __str__(self) -> str:
        return self.name


class Gallery(models.Model):
    """ класс модели галереи изображений """
    name = models.CharField(max_length=250)
    images = models.ManyToManyField(Photo)
    captions = models.TextField(max_length=255 ,blank=True)
    create_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=255)

    class Meta:
        ordering = ['name']

    def __str__(self) -> str:
        return self.name

culinary/blog/forms.py
from pyexpat import model
from django import forms
from .models import Coment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Coment
        exclude = ['creare_at', 'post']
        widgets = {
            'name': forms.TextInput(attrs={'placeholder':'Введите имя'}),
            'email': forms.EmailInput(attrs={'placeholder': 'Введите email'}),
            'website': forms.TextInput(attrs={'placeholder': 'Введите название сайта'}),
            'message': forms.Textarea(attrs={'placeholder': 'Введите сообщение'})
        }

culinary/contact/forms.py
from django import forms
from .models import ContactModel

class ContactForm(forms.ModelForm):
    
    class Meta:
        model = ContactModel
        fields = '__all__'

culinary/blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView
from .models import Post, Coment
from .forms import CommentForm

class HomeView(ListView):
    model = Post
    paginate_by: 9
    template_name = 'blog/home.html'


class PostListView(ListView):
    model = Post

    def get_queryset(self):
        return Post.objects.filter(category__slug=self.kwargs.get('slug')).select_related('category')
        

class PostDetailView(DetailView):
    model = Post
    context_object_name = 'post'
    slug_url_kwarg = 'post_slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CommentForm()
        return context


class CreateComment(CreateView):
    model = Coment
    form_class = CommentForm

    def form_valid(self, form):
        form.instance.post_id = self.kwargs.get('pk')
        self.object = form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return self.object.post.get_absolute_url()
        

culinary/contact/views.py
from django.shortcuts import render
from django.views import View
from django.views.generic import CreateView

from .models import About, ContactLink
from .forms import ContactForm

class ContactView(View):
    def get(self, request):
        contacts = ContactLink.objects.all()
        form = ContactForm()
        return render(request, 'contact/contact.html', {'contacts':contacts, 'form':form})


class CreateContact(CreateView):
    form_class = ContactForm
    success_url = '/'


class AboutView(View):
    def get(self, request):
        about = About.objects.last()
        return render(request, 'contact/about.html', {'about': about})

culinary/gallery/views.py
from django.shortcuts import render

# Create your views here.

culinary/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">


  <head>
    <meta charset="UTF-8" />
    <meta name="description" content="Culinary_blog Template" />
    <meta name="keywords" content="html, creative, culinaryBlog" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Blog{% endblock %}</title>
    <link
      href="https://fonts.googleapis.com/css?family=Nunito+Sans:300,400,600,700,800,900&display=swap"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Unna:400,700&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="{% static 'css/bootstrap.min.css' %}"
      type="text/css"
    />
    <link
      rel="stylesheet"
      href="{% static 'css/font-awesome.min.css' %}"
      type="text/css"
    />
    <link
      rel="stylesheet"
      href="{% static 'css/elegant-icons.css' %}"
      type="text/css"
    />
    <link
      rel="stylesheet"
      href="{% static 'css/owl.carousel.min.css' %}"
      type="text/css"
    />
    <link
      rel="stylesheet"
      href="{% static 'css/slicknav.min.css' %}"
      type="text/css"
    />
    <link
      rel="stylesheet"
      href="{% static 'css/style.css' %}"
      type="text/css"
    />
  </head>

  <body>
    <div id="preloader">
      <div class="loader"></div>
    </div>

    {% include 'blog/include/left_nav.html' %}
    

    {% include 'header.html' %}

    {% block content %} {% endblock content %} 
    
    {% include 'footer.html' %}

    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>

culinary/templates/blog/home.html
{% extends 'base.html' %} 
{% block content %}

<section class="categories spad">
  <div class="categories__post">
    <div class="container">
      <div class="row" style="background: rgb(247, 246, 231);">
        <div class="col-lg-8 col-md-8">
          {% for post in post_list %} 
          {% if forloop.first %}
          <div class="categories__post__item categories__post__item--large">
            <div
              class="categories__post__item__pic set-bg"
              data-setbg="{{ post.image.url }}"
            >
              <div class="post__meta">
                <h4>{{ post.created_at|date:'d' }}</h4>
                <span>{{ post.created_at|date:'M' }}</span>
              </div>
            </div>
            <div class="categories__post__item__text">
              <ul class="post__label--large">
                <li>{{ post.category }}</li>
              </ul>
              <h3>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
              </h3>
              <ul class="post__widget">
                <li><span>{{ post.author }}</span></li>
                <li>Время чтения: 4 мин</li>
                <li>20 коментариев </li>
              </ul>
              <p>{{ post.text|slice:'250' }}...</p>
              <a href="{{ post.get_absolute_url }}" class="primary-btn"
                >Читать пост</a
              >
            </div>
          </div>
          {% endif %} 
          {% endfor %}
          <div class="row">
            <div class="col-sm-6 col-md-6 col-lg-6">
              {% for post in post_list %} 
              {% if forloop.counter <= 4 and forloop.counter > 1 %}
              <div class="categories__post__item">
                <div
                  class="categories__post__item__pic small__item set-bg"
                  data-setbg="{{post.image.url}}"
                >
                  <div class="post__meta">
                    <h4>{{ post.created_at|date:'d' }}</h4>
                    <span>{{ post.created_at|date:'M' }}</span>
                  </div>
                </div>
                <div class="categories__post__item__text">
                  <span class="post__label">{{ post.category }}</span>
                  <h3>
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                  </h3>
                  <ul class="post__widget">
                    <li><span>{{ post.author }}</span></li>
                    <li>Время чтения: 5 мин</li>
                    <li>20 коментариев</li>
                  </ul>
                  <p>{{ post.text|slice:":250" }}...</p>
                </div>
              </div>
              {% endif %} 
              {% endfor %}
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6">
              {% for post in post_list %} {% if forloop.counter > 4 %}
              <div class="categories__post__item">
                <div
                  class="categories__post__item__pic small__item set-bg"
                  data-setbg="{{ post.image.url }}"
                >
                  <div class="post__meta">
                    <h4>{{ post.created_at|date:"d" }}</h4>
                    <span>{{ post.created_at|date:"M" }}</span>
                  </div>
                </div>
                <div class="categories__post__item__text">
                  <span class="post__label">{{ post.category }}</span>
                  <h3>
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                  </h3>
                  <ul class="post__widget">
                    <li><span>{{ post.author }}</span></li>
                    <li>Время чтения: 4 мин</li>
                    <li>20 Comment</li>
                  </ul>
                  <p>{{ post.text|slice:":250" }}...</p>
                </div>
              </div>
              {% endif %} {% endfor %}
            </div>
          </div>
          <div class="col-lg-12 text-center">
            <div class="load__more__btn mb-3">
              <a href="#">Загрузить больше</a>
            </div>
          </div>
        </div>
         {% include 'blog/include/sidebar.html' %}
      </div>

     
    </div>
  </div>
</section>

{% endblock %}

culinary/templates/blog/include/left_nav.html
{% load menu_tags social_tags %}

<div class="humberger__menu__overlay"></div>
<div class="humberger__menu__wrapper">
    <div class="humberger__menu__logo">
        <a href="/"><img src="../../../static/img/humberger/humberger-logo.png" alt="#"></a>
    </div>
    <nav class="humberger__menu__nav mobile-menu">
        <ul>
            <li><a href="/">Главная</a></li>
            {% get_categories %}
            <li><a href="{% url 'contact:about' %}">Обо мне</a></li>
            <li><a href="{% url 'contact:contact' %}">Контакты</a></li>
        </ul>
    </nav>

    <div id="mobile__menu__wrap"></div>

    <div class="humberger__menu__about">
        <div class="humberger__menu__title sidebar__item__title">
            <h6>Обо мне</h6>
        </div>
        {% get_about as about %}
            <img src="{{ about.get_first_image }}" alt="#">
        <p>{{ about.mini_text|safe }}</p>
        <div class="humberger__menu__about__social sidebar__item__follow__links">
            {% get_social_links as social_links %}
            {% for item in social_links %}
                <a href="{{ item.link }}"><img class="contact-icon" src="{{ item.icon.url }}" alt=""></a>
            {% endfor %}
        </div>
    </div>
    <div class="humberger__menu__subscribe">
        <p>Подпишитесь на нашу рассылку и будьте в курсе вкусных тем</p>
        <form action="#">
          <input type="text" class="email-input" placeholder="Ваш email">
          <label for="agree-check">
            Я согласен с условиями
            <input type="checkbox" id="agree-check">
            <span class="checkmark"></span>
          </label>
          <button type="submit" class="site-btn">Подписаться</button>
        </form>
      </div>
    </div>
</div>

culinary/templates/blog/include/sidebar.html
{% load social_tags %}

<div class="col-lg-4 col-md-4">
  <div class="sidebar__item">
    <div class="sidebar__about__item">
      <div class="sidebar__item__title">
        <h6>Обо мне</h6>
      </div>
      {% get_about as about %}
      <img src="{{ about.get_first_image }}" alt="#" />
      <h6>
        Добро пожаловать! <br />
        <br />
        Меня зовут <span>{{ about.name }}</span>
      </h6>
      <p>{{ about.mini_text|safe }}</p>
      <a href="{% url 'contact:about' %}" class="primary-btn">Узнать больше</a>
    </div>
    <div class="sidebar__follow__item">
      <div class="sidebar__item__title">
        <h6>Подписаться</h6>
      </div>
      {% get_social_links as social_links %}
      <div class="sidebar__item__follow__links">
        {% for item in social_links %}
        <a href="{{ item.link }}"><img src="{{item.icon.url}}" alt="" /></a>
        {% endfor %}
      </div>
    </div>
    <div class="sidebar__item__banner">
        <img src="/static/img/sidebar/banner.jpeg" alt="banner">
    </div>
    <div class="sidebar__item__categories">
        <div class="sidebar__item__title">
            <h6>Категории</h6>
        </div>
        {% include 'blog/include/sidebar_category.html' %}
    </div>
    <div class="sidebar__subscribe__item">
        <div class="sidebar__item__title">
          <h6>Подписаться</h6>
        </div>
        <p>Подпишитесь на рассылку и наслаждайтесь прекрасными рецептами</p>
        <form action="#">
          <input type="text" class="email-input" placeholder="Ваш email">
          <label for="s-agree-check">
            Согласиться с правилами
            <input type="checkbox" id="s-agree-check">
            <span class="checkmark"></span>
          </label>
          <button type="submit" class="site-btn mb-3">Подписаться</button>
        </form>
      </div>
  </div>
</div>

culinary/templates/blog/include/sidebar_category.html
{% load menu_tags %}
<ul>
    {% get_list_category as category %}
    {% for node in category %}
    <li><a href="{% url 'blog:post_list' node.slug %}">{{ node.name }}</a></li>
    {% endfor %}
</ul>

culinary/templates/blog/include/tags/gallery_tag.html
<section class="hero">
    <div class="hero__slider owl-carousel">
      <div class="hero__item">
        <div class="container-fluid">
          <div class="row">
            {% for photo in photos %}
              <div class="col-lg-6 p-0">
                  <div class="hero__inside__item hero__inside__item--wide set-bg"
                       data-setbg="{{ photo.image.url }}">
                  </div>
              </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </section>

culinary/templates/blog/include/tags/recipes_tag.html
{% load menu_tags %}
<li>
    <a href="#">Рецепты</a>
    <div class="header__megamenu__wrapper">
        <div class="header__megamenu">
            {% for post in list_last_post %}
                <div class="header__megamenu__item">
                    <div class="header__megamenu__item--pic set-bg" data-setbg="{{post.image.url}}">
                        <div class="label">{{ post.category.name }}</div>
                    </div>
                    <div class="header__megamenu__item--text">
                        <h5>
                            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                        </h5>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</li>

culinary/templates/blog/include/tags/top_menu.html
{% load mptt_tags %}

<li class="dropdown">
  <a href="#">Категории</a>
  <ul class="dropdown__menu">
    {% recursetree list_category %}
    <li>
      <a class="dropdown-item" href="{% url 'blog:post_list' node.slug %}">{{ node.name }}</a>
      {% if not node.is_leaf_node %}
      <ul class="children">
        {{ children }}
      </ul>
      {% endif %}
    </li>
    {% endrecursetree %}
  </ul>
</li>

culinary/templates/blog/include/top_nav.html
{% load menu_tags %}

<nav class="header__menu">
    <ul>
        <li class="active"><a href="/">Главная</a></li>
        {% get_last_post %}
        {% get_categories %}
        <li><a href="{% url 'contact:about' %}">О нас</a> </li>
        <li><a href="{% url 'contact:contact' %}">Контакты</a></li>
    </ul>
</nav>

culinary/templates/blog/post_detail.html
{% extends 'base.html' %} 
{% load social_tags %} 

{% block content %}
<section class="single-post spad">
  <div class="single-post__hero set-bg" data-setbg="{{ post.image.url }}"></div>
  <div class="container">
    <div
      class="row d-flex justify-content-center"
      style="background: rgb(247, 246, 231)"
    >
      <div class="col-lg-8">
        <div class="single-post__title">
          <div class="single-post__title__meta">
            <h2>{{ post.created_at|date:"d" }}</h2>
            <span>{{ post.created_at|date:"M" }}</span>
          </div>
          <div class="single-post__title__text">
            <ul class="label">
              <li>{{ post.category }}</li>
            </ul>
            <h4>{{ post.title }}</h4>
            <ul class="widget">
              <li>by {{ post.author }}</li>
              <li>3 min read</li>
              <li>20 Comment</li>
            </ul>
          </div>
        </div>
        <div class="single-post__social__item">
          <ul>
            <li>
              <a href="#"><i class="fa fa-facebook"></i></a>
            </li>
            <li>
              <a href="#"><i class="fa fa-twitter"></i></a>
            </li>
            <li>
              <a href="#"><i class="fa fa-instagram"></i></a>
            </li>
            <li>
              <a href="#"><i class="fa fa-youtube-play"></i></a>
            </li>
          </ul>
        </div>
        <div class="single-post__top__text">
          <p>{{ post.text|truncatewords:20 }}</p>
        </div>
        <div class="single-post__recipe__details">
          {% for recipe in post.get_recipes %}
          <div class="single-post__recipe__details__option">
            <ul>
              <li>
                <h5><i class="fa fa-user-o"></i>Порции</h5>
                <span>{{ recipe.serves }}</span>
              </li>
              <li>
                <h5><i class="fa fa-clock-o"></i> Подготовка</h5>
                <span>{{ recipe.prep_time }}</span>
              </li>
              <li>
                <h5><i class="fa fa-clock-o"></i> Готовка</h5>
                <span>{{ recipe.cook_time }}</span>
              </li>
              <li>
                <a href="#" class="primary-btn"
                  ><i class="fa fa-print"></i> Читать</a
                >
              </li>
            </ul>
          </div>

          <div class="single-post__recipe__details__indegradients">
            <h5>Ингридиенты</h5>
            {{ recipe.ingredients|safe }}
          </div>
          <!-- <div class="single-post__recipe__details__direction">
                <h5>Приготовление</h5>
                {{ recipe.directions|safe }}
              </div> -->
          {% endfor %}
        </div>

        <div class="single-post__desc">
          <h4>приготовление:</h4>
          <p>{{ post.text }}</p>
        </div>
        <div class="single-post__tags">
          {% for tag in post.tags.all %}
          <a href="#">{{ tag.name }}</a>
          {% endfor %}
        </div>

        <div class="single-post__next__previous">
          <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6">
          
                <a r href="#">
                  <h6><span class="arrow_carrot-left"></span> Предыдущий пост</h6>
                  <div class="single-post__previous__meta">
                    <h4>29</h4>
                    <span>Окт</span>
                  </div>
                  <div class="single-post__previous__text">
                    <span>Завтраки</span>
                    <h5>Классика запекания мяса, <br/>З лучших идеи</h5>
                  </div>
                </a>
            
            </div>

            <div class="col-lg-6 col-md-6 col-sm-6">
              <a
                href="#"
                class="single-post__next"
              >
                <h6>Следующий пост <span class="arrow_carrot-right"></span></h6>
                <div class="single-post__next__meta">
                  <h4>13</h4>
                  <span>Сен</span>
                </div>
                <div class="single-post__next__text">
                  <span>Десерты</span>
                  <h5>Лучшие фруктовые идеи <br />Не пропустите</h5>
                </div>
              </a>
            </div>
          </div>
        </div>
        {% get_about as about %}
        <div class="single-post__author__profile">
          <div class="single-post__author__profile__pic">
            <img src="{{ about.get_first_image }}" alt="" />
          </div>
          <div class="single-post__author__profile__text">
            <h4>{{ about.name }}</h4>
            <p>{{ about.mini_text|safe }}</p>
            <div class="single-post__author__profile__social">
              {% get_social_links as social_links %} 
              {% for item in social_links%}
              <a href="{{ item.link }}"><img src="{{ item.icon.url }}" /></a>
              {% endfor %}
            </div>
          </div>
        </div>
        <div class="single-post__comment">
          <div class="widget__title">
            <h4>Комментарии: {{ post.get_comment.count }} </h4>
          </div>
          {% for comment in post.get_comment %}
          <div class="single-post__comment__item">
            <div class="single-post__comment__item__pic">
              <img src="/static/img/category/single-post/comment/comment-1.jpeg" alt="" />
            </div>
            <div class="single-post__comment__item__text">
              <h5>{{ comment.name }}</h5>
              <span>{{ comment.create_at }}</span>
              <p>{{ comment.message }}</p>
            </div>
          </div>
          {% endfor %}
        </div>
        <div class="single-post__leave__comment">
          <div class="widget__title">
            <h4>Оставить комментарий</h4>
          </div>
          <form
            action="{% url 'blog:create_comment' pk=post.id %}"
            method="post"
          >
            {% csrf_token %}
            <div class="input-list">
              {{ form.name }} {{ form.email }} {{ form.website }}
            </div>

            {{ form.message }}
            <button type="submit" class="site-btn mb-5">Отправить</button>
          </form>
        </div>
      </div>
    </div>
  </div>
 </section>
{% endblock %}

culinary/templates/blog/post_list.html
{% extends 'base.html' %} 
{% block content %}

<section class="categories categories__grid spad">
  <div class="categories__post">
    <div class="container">
      <div class="categories__grid__post">
        <div class="row" style="background: rgb(247, 246, 231)">
          <div class="col-lg-8 col-md-8">
            <div class="breadcrumb__text">
              <h2>
                Категория: <span>{{ post_list.first.category.name }}</span>
              </h2>
              <div class="breadcrumb__option">
                <a href="/">Главная</a>
                <span>Рецепты</span>
              </div>
            </div>
            <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6">
              {% for post in post_list %}
              <div class="catregories__post__item">
                <div
                  class="categories__post__item__pic small__item set-bg"
                  data-setbg="{{ post.image.url }}"
                >
                  <div class="post__meta">
                    <h4>{{ post.created_at|date:"d" }}</h4>
                    <span>{{ post.created_at|date:"M" }}</span>
                  </div>
                </div>
                <div class="categories__post__item__text">
                  <span class="post__label">{{ post.category }}</span>
                  <h3>
                    <a href="{{ post.get_absolute_url }}">{{post.title}}</a>
                  </h3>
                  <ul class="post__widget">
                    <li><span>{{ post.author }}</span></li>
                    <li>Время чтения: 3 мин</li>
                    <li>12 комментариев</li>
                  </ul>
                  <p>{{ post.text|slice:'250' }}...</p>
                </div>
              </div>
              {% endfor %}
              
            </div>
            <div class="col-lg-12 text-center mb-3">
              <div class="load__more__btn">
                <a href="#">Читать больше</a>
              </div>
            </div>
          </div>
          </div>
          {% include 'blog/include/sidebar.html' %}
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

culinary/templates/contact/contact.html
{% extends 'base.html' %} 

{% block content %}

<div class="contact spad">
  <div class="container">
    <div class="contact__text">
      <div class="row">
        <div class="col-lg-12">
          <div class="breadcrumb__text">
            <h2>Контакты</h2>
            <div class="breadcrumb__option">
              <a href="#">На главную</a>
              <span>Контакты</span>
            </div>
          </div>
        </div>
      </div>
      <div class="row d-flex justify-content-between">
        <div class="col-lg-6 col-md-6">
          <div class="contact__map">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2540.3923473803734!2d30.522106115621472!3d50.452418195104265!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40d4ce506aa860c9%3A0xee2ec1ecbbb48832!2z0YPQuy4g0JzQuNGF0LDQudC70L7QstGB0LrQsNGPLCA20JIsINCa0LjQtdCyLCAwMjAwMA!5e0!3m2!1sru!2sua!4v1664894126098!5m2!1sru!2sua" width="600" height="400" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
          </div> 
          <div class="contact__widget">
            <ul>
                {% for contact in contacts %}
                    <li>
                        <i class="fa fa-map-marker"></i>
                        <img class="contact_icon" src="{{ contact.icon.url }}" alt="#">
                        <span>{{ contact.name }}</span>
                    </li>
                {% endfor %}
            </ul>
          </div>
        </div>
        <div class="col-lg-5 col-md-5">
            <div class="contact__form">
                <div class="contact__form__title">
                    <h2>Написать мне</h2>
                    <!-- <p>
                        Для вопросов и предложений воспользуйтесь контактной формой.
                    </p> -->
                </div>
                <form action="{% url 'contact:feedback' %}" method="post">
                    {% csrf_token %}
                    {{ form }}
                    <button class="site-btn" type="submit">Отправить</button>
                </form>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}